<!DOCTYPE html>
<html lang="pt-BR">
<head>
    <title>Edição em Massa de Valores e TTL</title>
    <link rel="stylesheet" href="/ui-library/css/standard.css">
</head>
<body>
    <h1 class="pul-heading pul-heading--h1">Editar Valores e TTL para Registros DNS Selecionados</h1>
    <form method="post" action="../scripts/massEditHandler.php" class="pul-form">
        <?php
        // Agrupamento de registros por tipo
        $groupedRecords = [];
        foreach ($dnsRecords as $record) {
            $type = $record['type'];
            $groupedRecords[$type][] = $record;
        }

        // Geração de campos de entrada para cada grupo de tipo de registro
        foreach ($groupedRecords as $type => $records): ?>
            <div class="pul-form-row">
                <h2 class="pul-heading pul-heading--h2">Registros <?= htmlspecialchars($type) ?></h2>
                <ul class="pul-list">
                    <?php foreach ($records as $record): ?>
                        <li><?= htmlspecialchars($record['name']) ?></li>
                        <input type="hidden" name="record_ids[<?= htmlspecialchars($type) ?>][]" value="<?= htmlspecialchars($record['id']) ?>">
                    <?php endforeach; ?>
                </ul>
                <label for="<?= htmlspecialchars($type) ?>_content" class="pul-form-label">Novo Conteúdo:</label>
                <input type="text" name="content[<?= htmlspecialchars($type) ?>]" id="<?= htmlspecialchars($type) ?>_content" class="pul-input-text" placeholder="Insira o valor desejado">
                <label for="<?= htmlspecialchars($type) ?>_ttl" class="pul-form-label">Novo TTL:</label>
                <input type="text" name="ttl[<?= htmlspecialchars($type) ?>]" id="<?= htmlspecialchars($type) ?>_ttl" class="pul-input-text" placeholder="Insira o TTL desejado">
            </div>
        <?php endforeach; ?>
        
        <div class="pul-form-footer">
            <button type="submit" class="pul-button pul-button--primary">Salvar Alterações</button>
        </div>
    </form>
</body>
</html>
